### ISSUE TITLE
Indicator on Governance

### ISSUE THREAD

**Issue by kjetilk** [DPGAlliance/DPG-Standard#102]
I believe the standard needs a section on governance. It is entirely possible that open projects maintain a rather restrictive policy for decision-making, changes to the project, inclusion and exclusion of parties. Open Source projects may follow many different models in this area, including the "Benevolent Dictator for Life", who might be the founder of the project. I think that may be a problematic model, but given its prevalence, it might be difficult to exclude it. I think it is nevertheless important for the alliance to have that discussion.

Personally (and I should emphasize that I speak only for myself), I tend to think that a governance model that says something like 

"All projects must be governed by a multi-lateral decision body whose proceedings are public"

is a good minimum requirement. In this case, the least the BDfL is required to appoint others from different groups to guide the project.

**Comment by prajectory** [comment]
Hi, we are looking into this and will come back to you soon.

**Comment by kjetilk** [comment]
For an overview of commonly used governance in open source projects, Jono Bacon's book [The Art of Community](https://www.jonobacon.com/books/artofcommunity/) which can be downloaded from there, has a chapter on governance.

**Comment by kjetilk** [comment]
For future reference for the public, I would just like to follow up on this. When I submitted did, I did that as a private person with an interest in the topic. Since then, I have joined Alliance member Norad, and thus I have had the opportunity to further contribute to an effort around this topic. 

I have realized it is most likely inappropriate to attach a governance requirement to all DPGs, but that there are some that may have a wide impact that probably should have in some form. Internally, the Alliance is just about to set up a group to discuss this, and we hope to have something to publish in the next few months for a broad community discussion.

Meanwhile, I'll close this issue.

**Comment by prajectory** [comment]
Hi @kjetilk,

Appreciate this context and for taking the time to think about this > involving yourself actively in solving for this. That's exactly the kind of community we are building. I reopened this issue because while we have moved and evolved on our thinking, it is certainly not something we have closed entirely. Even if this doesn't change the standard in a big way but builds resources for those applying the standard to do good, it is a good outcome. 

Let's see what comes from the work group you have constituted. We can update this thread as you have more updates. Thanks! 

cc @tanuj-b
