### ISSUE TITLE
📝 🧑‍⚖ Expand acceptable content and data licenses to Creative Commons IGO variants

### ISSUE THREAD

**Issue by jwflory** [DPGAlliance/DPG-Standard#111]
# Summary

Add the Creative Commons IGO license variants as acceptable licenses for the DPG Standard.

# Background

Recently, I discovered variants of Creative Commons 3.0 licenses designed for nongovernmental agencies and international aid organizations. These licenses remain identical to their non-IGO counterparts with the exception of a clause that requires disagreements to be handled through meditation and arbitration. For this same reason, the 3.0 IGO licenses are _not_ superseded by the 4.0 international variants. Thus, this seems like a blind spot for projects and creative works using these licenses who may meet all other DPG Standard requirements, except this one.

Also worth noting that UNICEF is currently exploring an open access policy, which would use one of the 3.0 IGO variants as a default license. These means all works created by UNICEF staff, contractors, interns, volunteers, etc. will be licensed under one of these IGO licenses unless another license is explicitly selected.

# Details

The implementation is below:

* DPGAlliance/publicgoods-candidates#940

More context can also be found in the Creative Commons wiki:

https://wiki.creativecommons.org/wiki/Intergovernmental_Organizations#Can_intergovernmental_organizations_.28.22IGOs.22.29_use_CC_licenses.3F

# Outcome

* More comprehensive selection of acceptable licenses for the DPG Standard.
* Future-proofing compatibility with an open access policy for UNICEF.

**Comment by downeymj** [comment]
I would be happy to see the CC 3.0 IGO ports listed and clarified as included in the Standard; there is a non-trivial amount of existing content available under those ports.

It is probably drifting off-topic, but I would also take this opportunity for a reminder that the DPGS2 "Use of Approved Open Licenses" still is written in such a way where software and content do not have parity. OSD6 "No Discrimination Against Fields of Endeavor", used by OSI in evaluation of license approval, is generally seen as incompatible with restrictions such as those remaining when licensed under CC's Non-Commercial (NC) clauses, and -NC flagged works as a result can be considered unavailable for use by nonprofits and/or other charities as part of their programmatic work.

**Comment by prajectory** [comment]
The issue that this should be combined with when discussing is linked here. 

https://github.com/DPGAlliance/DPG-Standard/issues/96

**Comment by prajectory** [comment]
This change will entail adding IGO variants of licenses that already exist as a part of the standard. These are Creative Commons licenses. 
The licenses covered under this change are:
Content:
CC-BY-3.0-IGO (Creative Commons Attribution 3.0 IGO)
CC-BY-NC-3.0-IGO (Creative Commons Attribution Non Commercial 3.0 IGO)
CC-BY-NC-SA-3.0-IGO (Creative Commons Attribution Non Commercial Share Alike 3.0 IGO)
CC-BY-SA-3.0-IGO (Creative Commons Attribution Share Alike 3.0 IGO)
Data:
CC-BY-3.0-IGO (Creative Commons Attribution 3.0 IGO)
CC-BY-SA-3.0-IGO (Creative Commons Attribution Share Alike 3.0 IGO)

These will be added to the list of licenses. Before we execute the change, we would like to know what @christer-io thinks since he is the expert on licensing. 

The rationale is:
More comprehensive selection of acceptable licenses for the DPG Standard.
Future-proofing compatibility with an open access policy for UNICEF.

We are opening this up for community discussion as well.

**Comment by jwflory** [comment]
It is also worth noting that the 4.0 family does not supersede the 3.0 IGO port and that the 3.0 IGO port contains the curing provision that already exists in the 4.0 family of licenses (but not other 3.0 licenses).

**Comment by jwflory** [comment]
@prajectory Not sure I understand the question. This addition to the license list would not impact the 4.0 family of licenses.

Previously, I was pointing out that the 3.0 IGO licenses share more in common with other 4.0 family of licenses than they do with the 3.0 family of licenses. Of course, I am not a lawyer however. 🙂

**Comment by prajectory** [comment]
https://github.com/DPGAlliance/publicgoods-candidates/pull/940 this change has been executed and therefore the issue is being closed.
