### ISSUE TITLE
7. Adherence to Privacy and Applicable Laws

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#69]
This indicator regularly causes issues because, it's not clear whether we're requesting compliance from the generic product or implementations. It's not clear which laws are "applicable". 

From conversation #66 we're proposing 3 options for discussion. 

1) Replace with --- Software must state to the best of its knowledge the product was developed in compliance with relevant laws based on the jurisdiction in which the generic product was developed. 
2) Delete this ---- ends up redundant with Indicator 9a or too implementation focused. 
3) Replace with --- PG must be developed in such a way as to facilitate compliance with relevant local laws for future implementations.

**Comment by Lucyeoh** [comment]
Note: We tend to focus exclusively on privacy laws during this assessment. 

Revised proposal: remove "international" remove "domestic". 

How do we decide "what's core" we use whatever registry is submitted.

**Comment by Lucyeoh** [comment]
Updated proposal -->> The digital solution must state to the best of its knowledge that the design of the core, generic solution complies with relevant privacy and applicable laws.

**Comment by Lucyeoh** [comment]
Opening up for two weeks for additional input from the community. We will inform the members of the DPGA's Internal Strategy Group (ISG) giving them an equal opportunity to comment. Reviewing these changes will happen quarterly. Consensus from the 2 co-leads and 2 technical leads (see Current Roles) will be required to accept or reject these proposals.

**Comment by tanuj-b** [comment]
> Updated proposal -->> The digital solution must state to the best of its knowledge that it is designed and developed to comply with relevant privacy laws.

Declare that the PG is compliant, but also put out a small statement on risks/potential harms? Sometimes there honestly is no control by the creators.

**Comment by Lucyeoh** [comment]
Updated version >>  The digital solution must enable compliance with relevant privacy laws. 

- Is this still as vague and confusing as the original question? 
- Would removing it weaken the standard too much - legal compliance captures some important requirements.

**Comment by prajectory** [comment]
We consulted with legal experts to understand their view of this indicator. Experts were - Morten Bergsmo who runs an open source project in international law and Justin Colannino who is a legal expert at Microsoft and Github. 
**Here are the inputs we received:** 

1. Narrow the scope and focus on what the DPGA is asking for; that way people won’t be confused/ intimidated/ repulsed. Keeping the language simple will also reduce churn and drop offs. 

2. Privacy is a good area to focus on. Additionally, using international and domestic both is redundant since some laws will supersede others. DPGA could either give indicative laws/ set a benchmark or keep it open for product owners to interpret what 'relevant privacy laws' means for the territory/ region they are in 

3. Don’t say relevant and applicable both - it means the same thing 

4. Make the language of questions related to this indicator more friendly and explanatory 

**We are making this change:** 
Digital Public Goods must be designed and developed to comply with applicable privacy laws. 

It will be tracked on https://github.com/DPGAlliance/DPG-Standard/issues/57 where other changes to the standards are also being incorporated.
