### ISSUE TITLE
Indicator 3. Clear Ownership

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#83]
In this indicator the sentence “Ownership of everything the project produces must be clearly defined and documented” could benefit from some clarity. Is this indicator directed at who owns the project itself, the algorithms, the application, design, UX-design, program, system or service? Or are we really taking “everything” into consideration?

If so, does this apply to content or data, produced or generated by user? One could argue that the project (through interaction with users) produce data.  Who owns the data automatically collected through interaction with the user? Or the data a user would have to share in order to be able to use the app, software or system?  Does this cover both PII and non-PII, such as name, age,address, geolocation, platform, make/ model of phone/ tablet/ browser, IMEI-number and so forth?

**Comment by prajectory** [comment]
Thank you for this input. 

We have accounted for the confusion the word "everything" might lead to. We have now changed the indicator to below mentioned text: 

_Ownership of **assets** that the digital public good produces must be clearly defined and documented. For example, through copyright, trademark or other publicly available information._

Assets can be digital and non-digital. Plus its a word that those who build technology solutions understand and comprehend well. Assets are everything that are owned by the solution creator. It covers PII and non PII both. There are other indicators that create that distinction of PII and non PII and in case of PII assets, take necessary documentation that mitigates the safety issue. 

If user is creating new "assets" for the digital solution by design, how that DPG reproduces that data depends on the kind of license that they have. It will change from one case to another. But the DPG owner still has the responsibility to prove the ownership of all of these self-built/ user generated assets.
