### ISSUE TITLE
Indicator 5.	Documentation

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#85]
I feel this indicator lacks a crucial point; the availability/ sharing of the documentation. This might feel obvious, but a clarification regarding who the information should be accessible to, how to ensure documentation integrity, updates, reviews and so forth would be of great value here. I would add “The project must have shareable documentation of the source code, use cases, and/or functional requirements”. It would not harm to clarify further, adding desired formats for instance. Some of the information might be publicly available, other parts might benefit from being shared between those who will actually work on the project in some kind of capacity. I would also like to see some kind of “Tool Bible” here, as in a listing of pre-approved tools used in the process of the project, being a part of the documentation. 

Also, there is a matter of language. Should they make the documentation and or their instructions available in their native tongue, or is there one, or more languages that are mandatory to use when delivering this? Who is responsible for translations?

**Comment by prajectory** [comment]
These are valid points. We wanted to keep the standard comprehensible and also not make it too detailed or verbose - making it inaccessible. Some of your suggestions have been accounted for https://github.com/DPGAlliance/DPG-Standard/blob/main/standard-questions.md in the questionary. Some of the words like "shareable" can be avoided since "open" would mean shareable. I understand your point about translations. So far we haven't come across a use-case like that but if we do, we will be mindful about the pertinent points you have put across. For now, the questionary does the job of going into the depth of this indicator.
