### ISSUE TITLE
Indicator 9.c	Protection from Harassment

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#92]
I would avoid using the word “mechanism” here, see 9.b for explanation. Again, it is pretty obvious what the intent behind this indicator is, but here we are crossing over in a UX functionality domain like blocking or reporting a user on Facebook. Although blocking and reporting an abuser will prevent you from being contacted by said user, or even seeing the persons posts, it does not by any means prevent or stop the harassment. 

Most social media, or other applications or services for that matter, do not offer any forms of functionality providing safety or security of underage users.

**Comment by prajectory** [comment]
Hi @llsandell

Thank you for suggesting these changes. We have made changes to the standard as per these suggestions.
__________________

(9b) (9c) Mechanism as a term can be confusing since it has different implications for technologists vs non technologists. Since the standard deals in depth with the design, it is paramount that we clarify any confusion that language may be causing. The Standard Council considered other terms that would be more appropriate - policies, processes, systems.

More details at https://github.com/DPGAlliance/DPG-Standard/pull/120

Please keep us posted.
