### ISSUE TITLE
Are there any creative commons licenses we do NOT want to accept

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#94]
Today the standard [indicator 2 ](https://github.com/DPGAlliance/DPG-Standard/blob/main/standard.md) only requires that "the use of a Creative Commons license".

The rest of the components are currently "encouraged" - While we encourage projects to use a license that allows for both derivatives and commercial reuse (CC-BY and CC-BY-SA), or dedicate content to the public domain (CC0); licenses that do not allow for commercial reuse (CC-BY-NC and CC-BY-NC-SA) are also accepted. 

This discussion is to see if there are any CC licenses we feel would exclude a project from DPG status.

**Comment by lacabra** [comment]
@Lucyeoh: please refer to the explicit [list of approved licenses](https://github.com/unicef/publicgoods-candidates/blob/main/docs/licenses.md). If a license is not listed there, it is not accepted. Also please note that some CC licenses are accepted for `content` but that same license is not acceptable for `data`, so each section explicitly lists its own acceptable licenses.

I am supportive of amending the text of the indicator to more clearly capture this, but changing the list of approved licenses would be a major change.

**Comment by nathanbaleeta** [comment]
@Lucyeoh here is a list of the [non-conformant licenses](https://opendefinition.org/licenses/nonconformant/) we currently refer to.

**Comment by downeymj** [comment]
I thought I should a reminder in writing that CC's noncommercial (NC) licenses are both on the "list of approved licenses" and the "list of the non-comformant licenses". IANAL but it has long been my understanding that CC's NC licenses would not allow use by, for example, NGOs using a tool for fundraising management since revenue-generating activity, even by nonprofits, is considered a commercial activity. For more on this topic, see: https://dustycloud.org/blog/noncommercial-doesnt-compose/

**Comment by prajectory** [comment]
We will be taking this in the discussion in next standard council. There might be some reason to believe that we need to amend the language to clarify it further.

**Comment by prajectory** [comment]
We are adding some of the IGO variant licenses to the list of acceptable licenses. These are referred in #111 
Other than that NC licenses that we already accept are as explicitly mentioned as possible in the standard. The standard is read by many non technical folks with limited understanding of open source licensing. For that reason, it will be more helpful for this information to rest in the help centre. @jwflory I will need your help in articulating some of the indicators so that we receive more robust documentation from the applicants. I shall be in touch for that. Adding a tag here and keeping this issue open until we resolve this through the help centre.

**Comment by jwflory** [comment]
@prajectory I don't understand your ask. Is this different from what is already proposed in DPGAlliance/publicgoods-candidates#940?

**Comment by prajectory** [comment]
This change was executed in https://github.com/DPGAlliance/publicgoods-candidates/pull/940 and this issue has been closed for the same reason.
